version: '2'
services:
  couchdb:
    image: bitnami/couchdb:2
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '5984:5984'
      - '4369:4369'
      - '9100:9100'
    volumes:
      - couchdb_data:/bitnami/couchdb
volumes:
  couchdb_data:
    driver: local
